# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-10 08:14
from __future__ import unicode_literals

from django.db import migrations


def add_pycontw2016(apps, schema_editor):
    Conference = apps.get_model('conferences', 'Conference')
    db_alias = schema_editor.connection.alias
    Conference.objects.using(db_alias).create(
        id=1, name='PyCon Taiwan 2016', slug='pycontw-2016',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=add_pycontw2016,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
