# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_conference_initial_data'),
        ('events', '0004_add_keynoteevent_squashed_0007_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredevent',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='conference'),
            preserve_default=False,
        ),
    ]
